### PR TITLE
issue 89

### PR DESCRIPTION
**Pull request by fabioperrella**
This is a patch for #89 

Before redirecting to CAS, it checks if session_store is memcache and if it is alive, otherwise does not redirect do CAS to prevent a redirect loop

### CODE REVIEW

**Comment by nbudin** [comment]
Thanks @fabioperrella!  This is a very comprehensive solution to a vexing problem, and in addition it has a good refactor of some of the weirder parts of the SingleSignOut module.

The Travis build is failing, but I think it's not your fault - it seems like the version of Ruby we're running on ships with a version of Rubygems that just doesn't work with our gemspec.  I'm going to drop 1.9.3 support and add some newer Ruby versions and see if it works.

**Comment by fabioperrella** [comment]
great, thank you!

**Comment by nbudin** [comment]
Sorry for dropping this on the floor for so long!  I'm going to just go ahead and merge this feature.

**Comment by nbudin** [comment]
I've just released 1.8.0 with this patch.  Thanks very much!

**Pull request merged**
